# -*- coding: utf-8 -*-
"""Eksperimen MSML

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pkJ_8xI0lu7dK7aNPkVg6kPjLw9mTL-D

# **1. Perkenalan Dataset**

Tahap pertama, Anda harus mencari dan menggunakan dataset dengan ketentuan sebagai berikut:

1. **Sumber Dataset**:  
   Dataset yang digunakan adalah Food Delivery Dataset yang menyimulasikan operasional pengiriman makanan. Dataset ini dipilih karena sangat relevan dengan industri lokal dan memiliki tantangan dunia nyata seperti data kosong (missing values) serta tipe data campuran (kategorikal dan numerikal).
Tujuan dari eksperimen ini adalah memprediksi status pesanan (misalnya: Completed atau Cancelled) berdasarkan fitur seperti jarak, waktu, dan cuaca.

# **2. Import Library**

Pada tahap ini, Anda perlu mengimpor beberapa pustaka (library) Python yang dibutuhkan untuk analisis data dan pembangunan model machine learning atau deep learning.
"""

#Type your code here
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Library untuk Preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
from sklearn.impute import SimpleImputer
import joblib # Untuk menyimpan objek scaler/encoder nantinya

# Pengaturan visualisasi
sns.set_theme(style="whitegrid")
import warnings
warnings.filterwarnings('ignore')

"""# **3. Memuat Dataset**

Pada tahap ini, Anda perlu memuat dataset ke dalam notebook. Jika dataset dalam format CSV, Anda bisa menggunakan pustaka pandas untuk membacanya. Pastikan untuk mengecek beberapa baris awal dataset untuk memahami strukturnya dan memastikan data telah dimuat dengan benar.

Jika dataset berada di Google Drive, pastikan Anda menghubungkan Google Drive ke Colab terlebih dahulu. Setelah dataset berhasil dimuat, langkah berikutnya adalah memeriksa kesesuaian data dan siap untuk dianalisis lebih lanjut.

Jika dataset berupa unstructured data, silakan sesuaikan dengan format seperti kelas Machine Learning Pengembangan atau Machine Learning Terapan
"""

#Type your code here
file_path = 'synthetic_fooddelivery_dataset.csv'
df = pd.read_csv(file_path)

print("Ukuran dataset:", df.shape)
display(df.head())

"""# **4. Exploratory Data Analysis (EDA)**

Pada tahap ini, Anda akan melakukan **Exploratory Data Analysis (EDA)** untuk memahami karakteristik dataset.

Tujuan dari EDA adalah untuk memperoleh wawasan awal yang mendalam mengenai data dan menentukan langkah selanjutnya dalam analisis atau pemodelan.
"""

# 3. Visualisasi Distribusi Target
target_col = 'Status_Pesanan'

if target_col in df.columns:
    plt.figure(figsize=(6, 4))
    sns.countplot(data=df, x=target_col)
    plt.title('Distribusi Status Pesanan')
    plt.show()
else:
    print(f"Kolom {target_col} tidak ditemukan. Silakan sesuaikan nama kolomnya.")

"""# **5. Data Preprocessing**

Pada tahap ini, data preprocessing adalah langkah penting untuk memastikan kualitas data sebelum digunakan dalam model machine learning.

Jika Anda menggunakan data teks, data mentah sering kali mengandung nilai kosong, duplikasi, atau rentang nilai yang tidak konsisten, yang dapat memengaruhi kinerja model. Oleh karena itu, proses ini bertujuan untuk membersihkan dan mempersiapkan data agar analisis berjalan optimal.

Berikut adalah tahapan-tahapan yang bisa dilakukan, tetapi **tidak terbatas** pada:
1. Menghapus atau Menangani Data Kosong (Missing Values)
2. Menghapus Data Duplikat
3. Normalisasi atau Standarisasi Fitur
4. Deteksi dan Penanganan Outlier
5. Encoding Data Kategorikal
6. Binning (Pengelompokan Data)

Cukup sesuaikan dengan karakteristik data yang kamu gunakan yah. Khususnya ketika kami menggunakan data tidak terstruktur.
"""

# Menentukan pembagian kolom berdasarkan tipe datanya
target_col = 'Status_Pesanan'
kolom_numerikal = ['Harga_Pesanan', 'Jarak_Kirim_KM', 'Waktu_Tunggu_Menit', 'Rating_Pelanggan']
kolom_kategorikal = ['Kategori_Menu', 'Status_Promo', 'Tingkat_Keluhan']
kolom_buang = ['ID_Pesanan', 'Waktu_Transaksi', 'Ulasan_Teks']

# Memastikan dataset tidak berantakan, kita copy dataframe
df_clean = df.copy()

# 1. Menghapus kolom yang tidak relevan untuk ML tabular (ID dan Teks deskriptif)
df_clean = df_clean.drop(columns=[col for col in kolom_buang if col in df_clean.columns])

# 2. Menangani Missing Values
# Mengisi angka kosong dengan median, dan kategori kosong dengan modus
imputer_num = SimpleImputer(strategy='median')
imputer_cat = SimpleImputer(strategy='most_frequent')

df_clean[kolom_numerikal] = imputer_num.fit_transform(df_clean[kolom_numerikal])
df_clean[kolom_kategorikal] = imputer_cat.fit_transform(df_clean[kolom_kategorikal])

# 3. Encoding Data Kategorikal
# Mengubah teks kategori menjadi kolom numerik (0 dan 1)
df_clean = pd.get_dummies(df_clean, columns=kolom_kategorikal, drop_first=True)

# Label Encoding untuk Target (mengubah misal 'Completed'/'Cancelled' jadi 0/1)
le = LabelEncoder()
df_clean[target_col] = le.fit_transform(df_clean[target_col])

# 4. Normalisasi / Standarisasi Fitur Numerik
# Menyamakan skala jarak, harga, menit, dan rating agar model tidak bias
scaler = StandardScaler()
df_clean[kolom_numerikal] = scaler.fit_transform(df_clean[kolom_numerikal])

# 5. Memisahkan Fitur (X) dan Target (y)
X = df_clean.drop(columns=[target_col])
y = df_clean[target_col]

print("Data siap! Ukuran X:", X.shape, "Ukuran y:", y.shape)
display(X.head())

# (Opsional) Menyimpan data yang sudah bersih untuk di-cek
# df_clean.to_csv("food_delivery_cleaned.csv", index=False)