name: Data Preprocessing Pipeline

on:
  push:
    branches:
      - main  # Action akan berjalan setiap kali ada push ke branch main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.7'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas scikit-learn numpy

    - name: Run preprocessing script
      run: |
        python preprocessing/automate_adi.py

    - name: Commit and Push cleaned data
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add preprocessing/dataset_preprocessing/food_delivery_cleaned.csv
        # Hanya commit jika ada perubahan pada file
        git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update cleaned dataset"
        git push